### ISSUE TITLE
라이센스 정보에 대해 문의드립니다.

### ISSUE THREAD

**Issue by hoibi** [nacean/sageun_food_store#1]
학교에서 opensource를 활용한 프로젝트를 하게 되어
사용하고 싶은데 라이센스가 명시되어 있지 않아 문의드립니다.
참고해도 될까요??

**Comment by nacean** [comment]
네 괜찮습니다~

-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2023-01-03 (화) 10:59:04 (GMT+09:00)
Subject: [nacean/sageun_food_store] 라이센스 정보에 대해 문의드립니다. (Issue #1)

학교에서 opensource를 활용한 프로젝트를 하게 되어
사용하고 싶은데 라이센스가 명시되어 있지 않아 문의드립니다.
참고해도 될까요??

**Comment by hoibi** [comment]
> 네 괜찮습니다~
> […](#)
> -----Original Message----- From: ***@***.***> To: ***@***.***>; Cc: ***@***.***>; Sent: 2023-01-03 (화) 10:59:04 (GMT+09:00) Subject: [nacean/sageun_food_store] 라이센스 정보에 대해 문의드립니다. (Issue #1) 학교에서 opensource를 활용한 프로젝트를 하게 되어 사용하고 싶은데 라이센스가 명시되어 있지 않아 문의드립니다. 참고해도 될까요?? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

넵, 감사합니다
